### ISSUE TITLE
Logout & undefined

### ISSUE THREAD

**Issue by gillesfabio** [claireso/journal#95]
There's no logout button/link in the admin 😢 (I'm on `master`)

BTW, cool admin! 👍 

Also, logged queries print `undefined`:

```
query: SELECT count(*) FROM photos undefined
query: SELECT * FROM photos ORDER BY id DESC OFFSET 0 LIMIT 10 undefined
```

Great job @claireso! Keep going! 👏

**Comment by claireso** [comment]
Thank you for your words of encouragement @gillesfabio!

The user session expires after 24 hours but yes, definitively, a button to logout is missing! I will add one as soon as possible.

For the `undefined` in logs it's `normal`. I do an ugly print [here](https://github.com/claireso/journal/blob/master/src/server/db/db.js#L14). The `undefined` value is not part of the query. The log is misleading...

I would love to have your feedback about the project. What do you think about the installation workflow? Do you find it simple enough? Do you plan to use it for your own journal? :smirk:

I hope your are going well and have found your new camera :blush:

**Comment by gillesfabio** [comment]
👍 Installation workflow is okay.

A few suggestions:

* Adding Docker to avoid installing dependencies (npm / Postgres) on computer
* Proposing a `config.dev.json` already setup with defaults for dev / demo / test
* Adding an option at bootstrap to use a pre-defined user password (for dev / demo / test)
* Adding a `Makefile` to abstract npm things

It could be cool to not have to think about config for a dev-like installation.

Example (no input, pre-defined password in `config.dev.json`):

```sh
$ npm run bootstrap --dev
```

It could be also called like this:

```sh
$ make bootstrap-dev
```

Or even (development commands only):

```sh
# Wraps npm install things
$ make install 

# Wraps npm bootstrap --dev (use pre-defined password)
$ make setup

# Wraps npm run build and npm run server
$ make serve
```

I don't use it yet but planned! (When I'd finally get my new camera 😅 Yes, yes... I know).

I can try to contribute a bit for Docker stuff if you agree with this suggestion.

I hope you're going well too! Have a great weekend! 🏄🕺

**Comment by claireso** [comment]
@gillesfabio

Finally the button to sign out is here! Hope you like it!

<img width="1279" alt="capture d ecran 2019-02-20 a 17 07 23" src="https://user-images.githubusercontent.com/961038/53106038-83f4b480-3532-11e9-9989-430768d53558.png">

I totally agree with your suggestions. I was also thinking about using Docker few weeks ago but I do not have enough time for this part. And your suggestions are more mature than mine.
So yes, feel free to make a pull request for that purpose.

**Comment by gillesfabio** [comment]
Thank you, @claireso! 👍 I'll send you a PR for the Docker stuff. Unfortunately, my JS isn't enough solid to help more.

**Comment by claireso** [comment]
Logged queries are now cleaned
